package ca.foc.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 
 * Entity to represent productSuggestion table
 * @author Claudia Rivera
 *
 */


@Entity
@Table(name="foc_product_suggestions")
public class ProductSuggestion {
	/**
	 * Integer autogenerated- primary key
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	/**
	 * Name of the product suggested
	 */
	private String name;
	/**
	 * Description of the product suggested
	 */
	private String description;
	
	
	public ProductSuggestion() {
		
	}
	public ProductSuggestion( String name, String description) {
		this.name = name;
		this.description = description;
		
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}


	public void setDescription(String description) {
		this.description = description;
	}

	

}
