version: 0.2
phases:
  build:
    commands:
    - echo Building Foods of Canada
    - mvn install
artifacts:
  files:
  - target/*.jar
  - scripts/*.sh
  - appspec.yml
  discard-paths: yes
cache:
  paths:
  - '/root/.m2/**/*'